
services:
  postgres:
    build: .
    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init_pgvector.sql:/docker-entrypoint-initdb.d/init_pgvector.sql
    environment:
      POSTGRES_USER: criminal
      POSTGRES_PASSWORD: root
      POSTGRES_DB: criminaldb